interest/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.tags_index, name="tags_index"),
    path("<int:pk>/", views.link_detail, name="link_detail"),
]

music/urls.py
from django.contrib import admin
from django.urls import path, include
from interest.views import dashboard, interest_view, interest_delete, tags_index, tag_detail

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path("links/", include("interest.urls")),
    path('rss/', include('rss.urls')),
    path('interests/delete', interest_delete, name='interests_delete'),
    path('interests/', interest_view, name='interests'),
    path('tagged/<str:label>', tag_detail, name='tag_detail'),
    path("tagged/", tags_index, name="tags_index"),
]

rss/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('feeds/', views.rest_feeds, name='rest-feeds'),
    re_path(r'^feeds/(?P<pk>[0-9]+)/$',
            views.rest_feeds_detail, name='rest-feeds-detail'),
    path('items/', views.rest_items, name='rest-items')
]

interest/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    twitter_username = models.CharField(max_length=200)
    twitter_id = models.IntegerField(null=True)
    objects = models.Manager()

    def __str__(self):
        return self.twitter_username

class HashTag(models.Model):
    hashtag = models.CharField(max_length=200)
    person = models.ManyToManyField(Person, through='Trusted')


class Trusted(models.Model):
    expert = models.ForeignKey(
        Person, related_name="expert", on_delete=models.DO_NOTHING)
    twittertag = models.ForeignKey(HashTag, on_delete=models.DO_NOTHING)


class Link(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    url = models.CharField(max_length=2000)
    code = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    class Meta:
        verbose_name = 'Link'
        verbose_name_plural = 'Links'

    def __str__(self):
        return self.title

    def get_classname(self):
        return 'Link'

machinetag/models.py
from django.db import models
from django.utils.text import slugify
from gm2m import GM2MField
from interest.models import Link
from rss.models import Feed

class MachineTag(models.Model):
    namespace = models.CharField(max_length=100, blank=True, default='')
    namespace_slug = models.SlugField(max_length=100, editable=False, default='')
    predicate = models.CharField(max_length=100, blank=True, default='')
    predicate_slug = models.SlugField(max_length=100, editable=False, default='')
    value = models.CharField(max_length=300, blank=True, default='')
    value_slug = models.SlugField(max_length=100, editable=False,  default='')
    label = models.CharField(
        max_length=600, editable=False, blank=True, default='')
    tagged = GM2MField(Link, Feed)
    objects = models.Manager()
    class Meta:
        verbose_name = 'Machine tag'
        verbose_name_plural = 'Machine tags'
        unique_together = (
            ('namespace', 'predicate', 'value')
        )
    def __str__(self):
        return '{0.namespace}:{0.predicate}={0.value}'.format(self)

    def save(self, *args, **kwargs):
        if not self.namespace_slug:
            self.namespace_slug = slugify(self.namespace)
        if not self.predicate_slug:
            self.predicate_slug = slugify(self.predicate)
        if not self.value_slug:
            self.value_slug = slugify(self.value)
        if not self.label:
            self.label = '{0.namespace_slug}:{0.predicate_slug}={0.value_slug}'.format(
                self)
        return super().save(*args, **kwargs)

interest/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from interest.models import Link
from machinetag.models import MachineTag
from rss.models import Feed
import re
# Create your views here.

def dashboard(request):
    tags = MachineTag.objects.order_by('label').all()
    context = {
        'machinetags': tags
    }
    return render(request, "dashboard.html", context)

def link_index(request):
    links = Link.objects.all()
    context = {
        'links': links
    }
    return render(request, 'link_index.html', context)


def link_detail(request, pk):
    link = Link.objects.get(pk=pk)
    context = {
        'link': link
    }
    return render(request, 'link_detail.html', context)


def interest_view(request):
    links = Link.objects.all()
    tags = MachineTag.objects.order_by(
        'label').all().prefetch_related('tagged')
    feeds = Feed.objects.all()
    context = {
        'tags': tags,
        'links': links,
        'feeds': feeds
    }
    if request.method == "POST":
        submitted_tags = request.POST.getlist("tag")
        submitted_links = request.POST.getlist("link")
        submitted_feeds = request.POST.getlist("feed")
        for tag in submitted_tags:
            selected_tag = MachineTag.objects.get(pk=tag)
            for link in submitted_links:
                selected_link = links.get(pk=link)
                selected_tag.tagged.add(selected_link)
            for feed in submitted_feeds:
                selected_feed = feeds.get(pk=feed)
                selected_tag.tagged.add(selected_feed)
    return render(request, "interests_index.html", context)


def interest_delete(request):
    if request.method == "POST":
        submitted_tag = request.POST.get("delete_tag")
        submitted_link = request.POST.get("delete_link")
        submitted_feed = request.POST.get("delete_feed")
        mtag = MachineTag.objects.get(id=submitted_tag)
        if submitted_link:
            link = Link.objects.get(id=submitted_link)
            mtag.tagged.remove(link)
        if submitted_feed:
            feed = Feed.objects.get(id=submitted_feed)
            mtag.tagged.remove(feed)
    return HttpResponseRedirect(reverse('interests'))

def tags_index(request):
    tags = MachineTag.objects.order_by('label').all().prefetch_related('tagged')
    context = {
        'machinetags': tags
    }
    return render(request, "dashboard.html", context)


def tag_detail(request, label):
    fragments = re.split(':|=', label)
    namespace = fragements[0]
    predicate = fragments[1]
    value = fragments[2]
    #All tags *:*=*
    if namespace == "*" and predicate == "*" and value == "*":
        tags = MachineTag.objects.order_by(
            'label').all().prefetch_related('tagged')
    #All predicate/value *:predicate:value
    elif namespace == "*":
        tags = MachineTag.objects.prefetch_related('tagged').get(predicate=predicate, value=value)
    #All namespace/value namespace:*=value
    #All namespace/predicate namespace:predicate=*
    # *:*=value
    # *:predicate=*
    # namespace:*=*

    tag = MachineTag.objects.prefetch_related('tagged').get(label=label)
    context = {
        'machinetag': tag
    }
    return render(request, "tag_detail.html", context)

interest/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<h1>Dashboard</h1>
{% for tag in machinetags %}
    <div>
        <h5>
            <a href="{% url 'tag_detail' tag.label %}">{{ tag.label }}</a>
        </h5>
    </div>
{% endfor %}
{% endblock %}

interest/templates/interests_index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<form action="" method="POST">
{% csrf_token %}
<h1>Machine Tags</h1>
{% for tag in tags %}
    <div>
        <h5>
            <input type="checkbox" name="tag" value="{{ tag.pk }}" />{{ tag.label }}
        </h5>
    </div>
{% endfor %}
<h1>Feeds</h1>
<div>
    {% for feed in feeds %}
    <div>
        <h5>
            <input type="checkbox" name="feed" value="{{ feed.pk }}" />{{ feed.url }}
        </h5>
    </div>
    {% endfor %}
</div>
<h1>Links</h1>
<div>
    {% for link in links %}
    <div>
        <h5>
            <input type="checkbox" name="link" value="{{ link.pk }}" />{{ link.title }}
        </h5>
    </div>
    {% endfor %}
</div>
   <button type="submit">Go</button>
</form>



<h1>Feeds</h1>
<div>
    {% for feed in feeds %}
    <div>
        <h5>
            {{ feed.url }}
        </h5>
        {% for mtag in feed.machinetag_set.all %}            
            <form action="{% url 'interests_delete' %}" method="POST">
            {% csrf_token %}
                <p>{{mtag.label}}</p>
                <input type="hidden" name="delete_tag" value="{{mtag.pk}}" />
                <input type="hidden" name="delete_feed" value="{{feed.pk}}" />
                <button type="submit">X</button>
            </form>
        {% endfor %}
    </div>
    {% endfor %}
</div>
<h1>Links</h1>
<div>
    {% for link in links %}
    <div>
        <h5>
            {{ link.title }}
        </h5>
        {% for mtag in link.machinetag_set.all %}
            <form action="{% url 'interests_delete' %}" method="POST">
            {% csrf_token %}
                <p>{{mtag.label}}</p>
                <input type="hidden" name="delete_tag" value="{{mtag.pk}}" />
                <input type="hidden" name="delete_link" value="{{link.pk}}" />
                <button type="submit">X</button>
            </form>
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}

interest/templates/link_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<h1>{{ link.title }}</h1>
<div>
    <div>
        <h5>About the link:</h5>
        <p>{{ link.description }}</p>
    </div>
</div>
{% endblock %}

interest/templates/link_index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Links</h1>
<div>
    {% for link in links %}
    <div>
        <h5>
            <a href="{% url 'link_detail' link.pk %}">
            {{ link.title }}
            </a>
        </h5>
        <p>{{ link.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

interest/templates/tag_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<h1>{{ machinetag.label }}</h1>
{% for item in machinetag.tagged.all %}
    {% if item.get_classname == 'Link' %}
        <p>{{item.title}}</p>
    {% endif %}
    {% if item.get_classname == 'Feed' %}
        <p>{{item.url}}</p>
    {% endif %}
{% endfor %}
<div>
   
</div>
{% endblock %}